SELECT
    Filial AS filial,
    Pedido AS pedido,
    "Pedido de Venda" AS pedido_de_venda,
    "Data integração WMS" AS data_integracao_wms,
    "Tipo da Ordem" AS tipo_da_ordem,
    Carga AS carga,
    Status AS status,
    "Status Descrição" AS status_descricao,
    Destinatário AS destinatario,
    item AS item,
    "Descrição do item" AS descricao_do_item,
    "Código do Setor do tem" AS codigo_do_setor_do_tem,
    "Descrição Setor do item" AS descricao_setor_do_item,
    "Qtde Original" AS qtde_original,
    "Qtde Expedida" AS qtde_expedida,
    "Qtde Ajustada" AS qtde_ajustada,
    "Data do Cancelamento" AS data_do_cancelamento,
    Usuário AS usuario,
    "Código Reference Text" AS codigo_reference_text,
    "Motivo Secondary Reference Text" AS motivo_secondary_reference_text,
    Box AS box,
    "Filial Destino" AS filial_destino,
    "Cidade Destino" AS cidade_destino,
    "Estado Destino" AS estado_destino,
    Volume AS volume,
    Peso AS peso,
    Descrição AS descricao,
    "Marcacao Pedido" AS marcacao_pedido,
    "Inventory Type ID" AS inventory_type_id
FROM df;