SELECT
    Filial AS filial,
    Local AS local,
    "Tipo do Local" AS tipo_do_local,
    Ocupação AS ocupacao,
    "Item Dedicado" AS item_dedicado,
    ILPN AS ilpn,
    Item AS item,
    Descrição AS descricao,
    "Qtd de Peças" AS qtd_de_pecas,
    "Tipo de EQP." AS tipo_de_eqp,
    Zona AS zona,
    "Put Allocation Zone ID" AS put_allocation_zone_id,
    Largura AS largura,
    Profundidade AS profundidade,
    Altura AS altura,
    "Max Volume" AS max_volume,
    "Max Peso" AS max_peso,
    "Inventory Type ID" AS inventory_type_id,
    "Inventory Attribute1" AS inventory_attribute1,
    CodSetorItem AS cod_setor_item,
    DescSetorItem AS desc_setor_item,
    DescMarcaItem AS desc_marca_item,
    "Item Volume" AS item_volume,
    Habilitado AS habilitado
FROM df;