SELECT
    Filial AS filial,
    "Data do Pedido" AS data_do_pedido,
    "Tipo de pedido" AS tipo_de_pedido,
    Wave AS wave,
    "Data locação pedido" AS data_locacao_pedido,
    Shipment AS shipment,
    "Filial Destino" AS filial_destino,
    Pedido AS pedido,
    "Status Pedido" AS status_pedido,
    "Pedido de Venda" AS pedido_de_venda,
    oLPN AS olpn,
    "Último Update oLPN" AS ultimo_update_olpn,
    TOTE AS tote,
    Tarefa AS tarefa,
    "Tarefa Status" AS tarefa_status,
    "Grupo de Tarefa" AS grupo_de_tarefa,
    Item AS item,
    Descrição AS descricao,
    "Local de Picking" AS local_de_picking,
    "Qtde. Peças Item" AS qtde_pecas_item,
    Volume AS volume,
    "Status oLPN" AS status_olpn,
    "Numero da Gaiola" AS numero_da_gaiola,
    BOX AS box,
    "Marcação de EAD" AS marcacao_de_ead,
    "Data Prevista Entrega" AS data_prevista_entrega,
    "Data Limite Expedição" AS data_limite_expedicao,
    "Inventory Type ID" AS inventory_type_id,
    "Cod Setor Item" AS cod_setor_item,
    "Desc Setor Item" AS desc_setor_item,
    "Audit Status" AS audit_status,
    "Marcação Pedido" AS marcacao_pedido
FROM df;